Repository googleapis/python-speech, pull requests merged in 2021-04, with the labels that each got.

#140 chore: sort classes
  google/cloud/speech_v1p1beta1/__init__.py
  synth.metadata
Labels: api: speech, cla: yes, context: none

#141 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: speech, cla: yes, context: full

#143 feat: Support for spoken punctuation and spoken emojis
  google/cloud/speech_v1p1beta1/__init__.py
  google/cloud/speech_v1p1beta1/proto/cloud_speech.proto
  google/cloud/speech_v1p1beta1/services/speech/async_client.py
  google/cloud/speech_v1p1beta1/services/speech/client.py
  google/cloud/speech_v1p1beta1/types/cloud_speech.py
  synth.metadata
  tests/unit/gapic/speech_v1p1beta1/test_speech.py
Labels: api: speech, cla: yes, context: partial

#147 chore: prevent normalization of semver versioning
  setup.py
Labels: api: speech, cla: yes

#149 chore(revert): revert preventing normalization
  setup.py
Labels: api: speech, cla: yes
