Repository googleapis/python-speech, pull requests merged in 2021-08, with the labels that each got.

#221 chore: require CODEOWNER review and up to date branches
  .github/sync-repo-settings.yaml
Labels: api: speech, automerge, cla: yes

#223 docs(samples): remove io dependency in transcribe samples
  samples/snippets/transcribe_async_file.py
  samples/snippets/transcribe_async_file_test.py
  samples/snippets/transcribe_async_gcs.py
  samples/snippets/transcribe_async_gcs_test.py
Labels: api: speech, cla: yes, samples

#232 chore: update python-samples-owners as samples codeowner
  .github/CODEOWNERS
Labels: api: speech, cla: yes, automerge, samples

#242 chore: migrate to main branch
  .github/sync-repo-settings.yaml
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  owlbot.py
Labels: api: speech, cla: yes
