Repository googleapis/python-speech, pull requests merged in 2021-11, with the labels that each got.

#284 chore: assign googleapis/cdpe-cloudai as codeowner
  .repo-metadata.json
Labels: api: speech, cla: yes

#276 docs(samples): a draft that refactors speech_to_storage_beta sample
  samples/snippets/speech_to_storage_beta.py
  samples/snippets/speech_to_storage_beta_test.py
Labels: api: speech, type: process, cla: yes, samples

#287 chore: update doc links from googleapis.dev to cloud.google.com
  .repo-metadata.json
  README.rst
Labels: api: speech, cla: yes, automerge
